using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class DeadLine : MonoBehaviour
{
    [SerializeField] private GameObject FixSphere;

    Vector3 hitPos;

    // Start is called before the first frame update
    void Start()
    {

    }

    // Update is called once per frame
    void Update()
    {

    }

    // ’n–Ê‚ÉÚG‚µ‚½‚Æ‚«‚ÉŒÄ‚Î‚ê‚é
    void OnCollisionEnter(Collision collision)
    {
        if (collision.gameObject.CompareTag("Player"))
        {
            //collision.contacts‚É•Û‘¶‚³‚ê‚Ä‚¢‚éÕ“Ëî•ñ‚ğ’²‚×‚é
            foreach (ContactPoint hitPoint in collision.contacts)
            {
                hitPos = hitPoint.point;   //Õ“ËêŠ‚ğæ“¾
            }

            Instantiate(FixSphere, hitPos, Quaternion.identity);
        }
    }
}